- name: google-dns
  host: 8.8.8.8
  port: 53
  proto: udp
  payload: dns

- name: github-ssh
  host: github.com
  port: 22, 80, 443
  proto: tcp

- name: demo-web
  host: example.com
  port: 80
  proto: tcp

- name: portquiz-http
  host: portquiz.net
  port: 80
  proto: tcp

- name: nmap-ssh
  host: scanme.nmap.org
  port: 22
  proto: tcp

- name: fail-demo
  host: 192.0.2.123
  port: 9999
  proto: tcp

- name: open-http
  host: example.com
  port: 80
  proto: tcp
  l7_check:
    type: http
    path: /

- name: refused-demo
  host: example.com
  port: 81
  proto: tcp

- name: filtered-demo
  host: 10.255.255.1
  port: 80
  proto: tcp